In [1]:
import gym
print(gym.__version__)

0.14.0


In [3]:
import keras
print(keras.__version__)

Using TensorFlow backend.


2.2.4


In [4]:
import random
import math
import numpy as np
from collections import deque

## Setting up the OpenAI Envronment

In [10]:
# Setup OpenAI gym interface
env = gym.make('CartPole-v0')

for i_episode in range(20):
    observation = env.reset()
    for t in range(1000):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        
        
    

[-0.01105492 -0.00755123 -0.00818696  0.00310161]
[-0.01120595  0.18768717 -0.00812493 -0.29215311]
[-0.00745221  0.38292402 -0.01396799 -0.58738742]
[ 2.06274248e-04  1.88000443e-01 -2.57157366e-02 -2.99137037e-01]
[ 0.00396628  0.38347933 -0.03169848 -0.59981802]
[ 0.01163587  0.18881486 -0.04369484 -0.31728579]
[ 0.01541217  0.38453105 -0.05004055 -0.62342206]
[ 0.02310279  0.58031465 -0.06250899 -0.93143563]
[ 0.03470908  0.38608942 -0.08113771 -0.65903246]
[ 0.04243087  0.58224128 -0.09431836 -0.9761206 ]
[ 0.05407569  0.38850217 -0.11384077 -0.71449211]
[ 0.06184574  0.1951248  -0.12813061 -0.45970055]
[ 0.06574823  0.00202474 -0.13732462 -0.20999228]
[ 0.06578873  0.19881573 -0.14152447 -0.54264648]
[ 0.06976504  0.39561334 -0.1523774  -0.87636099]
[ 0.07767731  0.20285426 -0.16990462 -0.63519841]
[ 0.0817344   0.0104583  -0.18260858 -0.40047193]
[ 0.08194356  0.2076371  -0.19061802 -0.74471154]
[ 0.0860963   0.01558509 -0.20551225 -0.51755431]
[ 0.08640801 -0.17614092 -0.215863

In [13]:
print(env.action_space) #See what actions are possible within this action space
print(env.observation_space) #See what observations are possible

Discrete(2)
Box(4,)


In [16]:
# training parameters

n_episodes = 1000 # How many episodes do we want to run
n_win_ticks = 195 # Whats the score we want to end the game at
max_env_steps = None 

gamma = 1.0 # discount factor, a consideration of future reward
epsilon = 1.0 #exploration, agent choosing an action it thinks has best longterm effect with a prob 1-(epsilon)
epsilon_min = 0.01
epsilon_decay = 0.995 # we want the exploration factor to reduce over time to the min
alpha = 0.01 # the learning rate, 0 means nothing new is learned and 1 means only take the most recent into consideration
alpha_decay = 0.01

batch_size = 64
monitor = False
quiet = False

# OpenAI Parameters
memory = deque(maxlen = 100000)
env = gym.make('CartPole-v0')
if max_env_steps is not None: env.max_episode_steps = max_env_steps

In [18]:
# Building the neural network
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

#Model definition
model = Sequential()
model.add(Dense(24,input_dim = 4, activation = 'relu'))
model.add(Dense(48, activation = 'relu'))
model.add(Dense(2, activation = 'relu'))
model.compile(loss = 'mse', optimizer = Adam(lr = alpha , decay = alpha_decay))



Instructions for updating:
Colocations handled automatically by placer.
